---
title: "Model transferability"
author: "Amber Meulenbeld"
date: "2023-02-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

load_files <- function(folder, target_name) {
  info <- str_split(folder, '-', simplify=TRUE)       # country, size
  file <- paste0(path, folder, target_name)
  data <- read.csv(file) %>%
    mutate(model = info[1],
           modelcountry = info[2],
           datacountry = info[3])
  return(data)
}
```

## R Markdown

```{r setup}
library(tidyverse)
library("PRROC")
```

```{r load models and data}
path <- "C:/Users/meule01a/OneDrive - Sanquin/A4 Project SanguinStats (OD)/07 Resultaten/results/"
folders <- list.dirs(path, full.names=FALSE, recursive=FALSE)

datalist <- lapply(folders, load_files, target_name='/prediction.csv')

for(i in 1:length(datalist)){
  colnames(datalist[[i]])[1] <- "Id"
}
```



```{r make figures}

geslacht <- c("male", "female")

currentDate <- format(Sys.time(), "%Y-%m-%d")
FolderName <- paste("C:/Users/meule01a/OneDrive - Sanquin/A4 Project SanguinStats (OD)/07 Resultaten/figures/", currentDate,sep="")
dir.create(FolderName)

FolderName <- paste("C:/Users/meule01a/OneDrive - Sanquin/A4 Project SanguinStats (OD)/07 Resultaten/figures/", currentDate,"/AUPR curves",sep="")
dir.create(FolderName)

for(i in 1:length(datalist)){
  for(j in 1:2){
  pr_curve <- pr.curve(scores.class0=datalist[[i]]$predicted_label[datalist[[i]]$sex==geslacht[j]], weights.class0=datalist[[i]]$original_label[datalist[[i]]$sex==geslacht[j]], curve = T)
#plot <- 
png(filename = paste0(FolderName, "/", datalist[[i]]$modelcountry[1], "-", datalist[[i]]$datacountry[1], "-", datalist[[i]]$model[1], "-", geslacht[j], ".png", sep= ""), height = 700, width = 700, units = "px")
plot(pr_curve, main = paste0(datalist[[i]]$modelcountry[1], "-", datalist[[i]]$datacountry[1], "-", datalist[[i]]$model[1], "-", geslacht[j], sep= ""))
dev.off()
  }
}
```

