---
title: "Plot for ECDHM 2023 abstract"
author: "Jarkko Toivonen"
date: "2023-05-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
result_dir <- "../results/all-results-2023-08-31"
fig_path <- "../results/figures/pdf"
# Note: coding of South-Africa and Australia is done in exact opposite way!!!!!!!!!!11
conv <- c(AU = "Australia2", AU2 = "Australia", BE ="Belgium", FI = "Finland", NL="Netherlands", SA="South-Africa", SA2="South-Africa2")
```

## R Markdown

```{r}
get_deferral_rates <- function(df) {
  df %>% 
    filter(label == "validate") %>%
    mutate(deferral_rate = `Deferred last donations` / `Donors`,
           sex = str_remove(Id, "rf-")) %>%
    select(sex, deferral_rate)
}
# deferral_rates <- tribble(
#   ~data_country, ~filename, 
#   "Australia", file.path(result_dir, "Model1-AU-AU/sizes.csv"),
#   "South-Africa", file.path(result_dir, "Model1-SA-SA/sizes.csv")
# )
deferral_rates <- enframe(conv) %>%
  rename(data_country = value, data_country_id=name) %>%
  #filter(data_country_id != "SA2") %>%
  mutate(filename = sprintf("%s/Model1-%s-%s/sizes.csv", result_dir, data_country_id, data_country_id))
deferral_rates <- deferral_rates %>%
  mutate(tmp = map(filename, function(f) get_deferral_rates(read_csv(f, show_col_types=FALSE)))) %>%
  unnest(tmp)
deferral_rates
```

```{r}
conv <- c("Australia\n own cutoff"="Australia2", "Australia\n EU cutoff"="Australia",
          "South Africa\n own cutoff"="South-Africa2", "South Africa\n EU cutoff"="South-Africa")
df <- deferral_rates %>% 
  select(-c(filename, data_country_id)) 
  #filter(!str_detect(data_country, "2")) %>% 
df %>%  pivot_wider(names_from = sex, values_from = deferral_rate)
g <- df %>%
  mutate(data_country = fct_recode(data_country, !!!conv)) %>%
  ggplot(aes(x=data_country, y=deferral_rate, fill=sex)) +
  geom_col(position = "dodge") +
  labs(x="Country", y="Deferral rate", fill="Sex") +
  geom_text(mapping=aes(label=sprintf("%.2f", deferral_rate)),  
            #hjust=1.1, 
            vjust=-0.3, position=position_dodge(width=0.9))
g
ggsave(file.path(fig_path, "deferral_rates.pdf"), g, width=180, height=120, unit="mm")
```

```{r}
helper <- function(filename) {
  df <- read_csv(filename, show_col_types=FALSE)
  df %>% select(sex = Sex, starts_with("AUPR"))
}
# auprs <- tribble(
#   ~model_country, ~data_country, ~filename,
#   "Australia", "Australia", file.path(result_dir, "Model1-AU-AU/summary.csv"),
# #  "Australia", "South-Africa", file.path(result_dir, "Model1-AU-SA/summary.csv"),
#   "South-Africa", "Australia", file.path(result_dir, "Model1-SA-AU/summary.csv"),
#   "South-Africa", "South-Africa", file.path(result_dir, "Model1-SA-SA/summary.csv")
# )
auprs <- expand_grid(model_country_id=names(conv), 
                     #data_country_id=(setdiff(names(conv), c("SA2", "SA")))) %>%
                     data_country_id=names(conv)) %>%
  #add_row(model_country_id="SA", data_country_id="SA") %>%
  #add_row(model_country_id="SA2", data_country_id="SA") %>%
  mutate(model_country = conv[model_country_id], 
         data_country = conv[data_country_id],
         filename = sprintf("%s/Model1-%s-%s/summary.csv", result_dir, model_country_id, data_country_id))
auprs <- auprs %>%
  mutate(tmp = map(filename, helper)) %>%
  unnest(tmp)
```

```{r}
both <- inner_join(auprs, deferral_rates, by=c("data_country", "data_country_id", "sex"))
```

```{r eval=FALSE}
g <-both %>%
  filter(!(str_starts(model_country, "South-Africa2") | str_starts(data_country, "South-Africa2"))) %>%
  ggplot(aes(deferral_rate, `AUPR value`, ymin=`AUPR low`, ymax=`AUPR high`, color=data_country, shape=model_country)) +
  geom_errorbar(position=position_jitter(width=0.01, height=0, seed=1)) +
  geom_point(position=position_jitter(width=0.01, height=0, seed=1)) +
  labs(x="Deferral rate", y="Area under PR curve", color="Data country", shape="Model country") +
  facet_wrap(~sex)
g
#ggsave(file.path(result_dir, "abstract_scatter.png"), g)
```

```{r Unadjusted}
# Only a single version from both South Africa and Australia.
g <- both %>%
  filter(!(model_country == "South-Africa2" | data_country == "South-Africa2")) %>%
  filter(!(model_country ==  "Australia2" | data_country == "Australia2")) %>%
  ggplot(aes(deferral_rate, `AUPR value`, ymin=`AUPR low`, ymax=`AUPR high`, color=data_country, shape=model_country)) +
  geom_errorbar(position=position_jitter(width=0.01, height=0, seed=1)) +
  geom_point(position=position_jitter(width=0.01, height=0, seed=1)) +
  labs(x="Deferral rate", y="Area under PR curve", color="Data country", shape="Model country") +
  facet_wrap(~sex)
g
ggsave(file.path(fig_path, "abstract_scatter_unadjusted.pdf"), g, width=180, height=120, unit="mm")
```

```{r Adjusted}
# Only a single version from both South Africa and Australia.
g <- both %>%
  filter(!(model_country == "South-Africa2" | data_country == "South-Africa2")) %>%
  filter(!(model_country ==  "Australia2" | data_country == "Australia2")) %>%
  mutate(across(starts_with("AUPR"), function(v) {v - deferral_rate})) %>%
  ggplot(aes(deferral_rate, `AUPR value`, ymin=`AUPR low`, ymax=`AUPR high`, color=data_country, shape=model_country)) +
  geom_errorbar(position=position_jitter(width=0.01, height=0, seed=1)) +
  geom_point(position=position_jitter(width=0.01, height=0, seed=1)) +
  labs(x="Deferral rate", y="Adjusted area under PR curve", color="Data country", shape="Model country") +
  facet_wrap(~sex)
g
ggsave(file.path(fig_path, "abstract_scatter_adjusted.pdf"), g, width=180, height=120, unit="mm")

```















